### PR TITLE
docs/fleerp: add general, alarms, templates, drivers, external services to settings

### PR DESCRIPTION
**Pull request by GrishaAngelov**
Part of #2

### CODE REVIEW

**Comment by mgenov** [comment]
The pages like "Начало", "Общи", "Настройки" could be moved into a single page named "Настройки" with different sections.

With the current design, the right menu is not looking good.

**Comment by GrishaAngelov** [comment]
This seems similar to #16, maybe once after we add the docs, then will make needed changes in separate PR, to be able to track better what we change ?

**Comment by mgenov** [comment]
Yes, it's similar to #16. I'm fine to be done after the migration phase if it's easier and will be faster.

**Review by mgenov — APPROVED** [review]
LGTM !

**Pull request merged**
